### ISSUE TITLE
track down power failure: power supply, ammeter, or tube?

### ISSUE THREAD

**Issue by heaventwig** [LaboratoryB/camfive#19]
## present functionality 
With potentiometer turned up to maximum, laser on, chiller running, and voltage at power supply verified to be running at 219.5V, pressing the red test-fire button beside the serial port on the power supply results in a sustained test-fire that appears to be underpowered, with the exterior ammeter display peaking at 6mA.
## expected functionality
The output from the power supply is supposed to be 40kV at 30mA. The Ammeter should read somewhere over 25mA at 90% power.

**Comment by Hurricos** [comment]
My understanding is that, unlike with the K40, the controller is partially responsible for requesting a particular laser power. Are you sure there aren't other controls in the way of a full fire?

Please post the picture of the labeling of the laser tube itself; we should do a comparison process like [this one](https://old.reddit.com/r/lasercutting/comments/l6812e/150w_co2_laser_ammeter/gkz6m65/) -- similar reading may have had you arrive at the 25mA figure.

**Comment by Hurricos** [comment]
Tube photos are [here](https://github.com/LaboratoryB/camfive/issues/5#issuecomment-2351722048), in particular:

![](https://private-user-images.githubusercontent.com/819200/367615195-51bf731b-3c9f-4fb9-be82-a334d8735094.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3MTY0NzYsIm5iZiI6MTcyNzcxNjE3NiwicGF0aCI6Ii84MTkyMDAvMzY3NjE1MTk1LTUxYmY3MzFiLTNjOWYtNGZiOS1iZTgyLWEzMzRkODczNTA5NC5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MzBUMTcwOTM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWVhMTZlNjllNWE5MWJhZWFkY2FkMWZmNzQ5ZDNkOWM5M2Y4MTc5NjgxYTdhYmY0YTBiYjA2MDYyYTAyOWEzZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.fMVAW-h0wuWbN4S7ceuJQq4wn6TttO5CzUcNfVZb8Bo)

**Comment by Hurricos** [comment]
(TL;DR the cost of a similarly-rated, 130W CO2 tube is in the $1500 range, power-supply included.)

**Comment by heaventwig** [comment]
Miguel, the tech support person at the camfive showroom in LA, says, after reviewing photos of the labels on tube (mfd 2014) and power supply (mfd 2019),
> Due to the 2014 manufacturing date, it is very likely that the laser tube needs to be replaced.
> Laser tube life time is about 4 to 5 years

**Comment by DaBlender** [comment]
So we do need a new tube, it’s fine to have lower watt if power supply matches. I quickly saw 100w for about $500 Amazon prime same manufacturer as current tube. The price jumps considerably at any more. 100w is more than enough for now. Once it’s positive cash flow money can be invested in more power if needed. It’s still over 10x my current production capacity

**Comment by Hurricos** [comment]
IMO you should buy once and buy right; buying a non-matched tube is kind of like throwing one away if you ever plan to replace it, given how they degrade.

IMO it's worth fitting the controller and evaluating where things stand after that for production. My guess is that Remington Arms didn't service the laser because it was working well enough for them when they stopped using it.

I was going to defer to others as to whether the activation and running voltages on the laser power supply matter, but:

> Powering CO2 and diode lasers are two entirely different beasts.
Co2 lasers require very high voltage power with simple to no control of the current. CO2 lasers are gas discharge (negative resistance) so they output very high voltages until the ionization potential is reached, then the device discharges and the voltage drops dramatically while the current ramps. These supplies are by no means standard power supply designs, are dangerous, and notoriously unreliable due to the high voltages.

From [here](https://forum.makerforums.info/t/exactly-what-varies-the-output-power-on-a-co2-laser/82691/2). I'm reading this as, so long as the power supply is intended for CO2 and reaches the activation voltage, it will work.

**Comment by DaBlender** [comment]
Upgrading the controller doesn’t fix the tube. It cannot cut at current levels. The tube and power supply were already upgrades. Tubes are pretty generic, which is why you can replace and upgrade them on most machines. I cannot justify paying thousands more up front for minimal gain. When demand calls I can just scale. If the machine cannot generate its own upgrades it’s not viable. I think it can. We went through factory tech support to confirm everything.

**Comment by DaBlender** [comment]
Yes. We are buying actual co2 laser power supplies if needed. There are very many to choose from at good prices. They are made exactly for this. Yes they are dangerous if not used properly like most things. It’s very hard to screw up given the simplicity. None of that is concerning to me at all.

**Comment by Hurricos** [comment]
FYI: here's the diagram of a standard 20kV K40 laser power supply: https://www.digikey.com/en/schemeit/project/k40-lps-2-EFKO7C8303M0/de675e80dec04bdbaa8120a921b0f599

**Comment by DaBlender** [comment]
What do you suggest we use this for?

**Comment by DaBlender** [comment]
Tube is exact replacement for original tube as specifies on stamp. RECI brand. Matching power supply.  Over voltage reduces tube life drastically. Cost for both via prime about $800? With three year protection on tube. I’m guessing we can measure and claim loss of amperage as a metric to justify replacement. Otherwise 40 day free replacement if anything goes wrong

**Comment by heaventwig** [comment]
Okay, the tech at FLEXMAX (camfive showroom in LA) was pretty confident the issue is the tube, and that it's expended in a way that's beyond our capacity to repair. That suggests we've completed this "track down the problem" issue, so I'm closing it and opening a new one ("tube: replace").
